### PR TITLE
Remove dependency on eui48, which depends on an outdated crate

### PR DESCRIPTION
**Pull request by eutampieri**

### CODE REVIEW

**Comment by eutampieri** [comment]
🎉

**Comment by eutampieri** [comment]
I haven’t bumped the crate version, so if you want to publish to crates.io you have to do it yourself ;)

**Comment by marirs** [comment]
Done sir. Thank you very much. I've pushed to crates as well. Updated to the latest DB too :)

Thanks again! Tc

**Comment by eutampieri** [comment]
Thank you!

**Pull request merged**
